[project]
name = "bert-score"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "matplotlib>=3.10.7",
    "numpy>=2.2.6",
    "packaging>=20.9",
    "pandas>=1.0.1",
    "sacrebleu>=2.5.1",
    "torch>=1.0.0",
    "tqdm>=4.31.1",
    "transformers>=3.0.0",
    "xformers>=0.0.33.post2",
]

[tool.setuptools]
packages = ["bert_score", "bert_score_cli"]

[tool.uv.workspace]
members = [
    ".",
]

[dependency-groups]
dev = []
